# Jekyll configuration for GitHub Pages
title: Newsgregator
description: Daily news summaries curated from various sources
theme: jekyll-theme-cayman

# GitHub Pages settings
baseurl: "/newsgregator" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .idea
  - .gradle
  - build
  - .git
  - src
  - gradle

# Include folders
include:
  - "docs"
  - "docs/*.md"

# Collections
collections:
  summaries:
    output: true
    permalink: /:collection/:name

# Default front matter for files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"
