# Jekyll configuration for GitHub Pages
title: Newsgregator
description: Daily news summaries curated from various sources
theme: jekyll-theme-cayman

# GitHub Pages settings
baseurl: "/newsgregator" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol, e.g. http://example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
# Include folders
#include:
#  - "docs"
#  - "docs/*.md"
# Process Markdown files in docs folder
#keep_files:
#  - docs

# Collections
collections:
  summaries:
    output: true
    permalink: /:collection/:name

# Default front matter for files
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"

