name: Daily News Summary

on:
  schedule:
    # Run daily at 8:00 AM UTC
    - cron: '0 8 * * *'
  workflow_dispatch:
    # Allow manual triggering

# Add permissions to allow writing to the repository
permissions:
  contents: write

jobs:
  generate-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew build -x test
      
      - name: Run News Summary Generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          ./gradlew run --args="--output docs"
          
      - name: Add Jekyll front matter to new files
        run: |
          for file in docs/*.md; do
            if [ "$file" != "docs/index.md" ] && ! grep -q "^---" "$file"; then
              echo "Adding front matter to $file"
              datepart=$(basename "$file" .md)
              tmp_file=$(mktemp)
              echo "---" > "$tmp_file"
              echo "layout: default" >> "$tmp_file"
              echo "title: News Summary for $datepart" >> "$tmp_file"
              echo "---" >> "$tmp_file"
              cat "$file" >> "$tmp_file"
              mv "$tmp_file" "$file"
            fi
          done
      
      - name: Commit and push if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update news summary [skip ci]" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
